lexicon_file = r'C:\Users\Sohail\Desktop\THIRD SEMESTER\DSA\FINAL PROJECT DSA\LEXICON\Search-Engine-DSA NEW\Search-Engine-DSA\lexicon.json'
docMapper_file = r'docmapper.json'
forward_barrel_dir = r'C:\Users\DELL\Desktop\Search-Engine-DSA\forward_barrels'
inverted_barrels_dir = r'C:\Users\DELL\Desktop\Search-Engine-DSA\inverted_barrels'
offset_barrels_dir = r'C:\Users\DELL\Desktop\Search-Engine-DSA\offset_barrels'
dataset_file = r'C:\Users\DELL\Desktop\University\Data Structures and Algorithms\Project\Medium Articles\medium_articles.csv'
new_doc_output_dir = r'Search-Engine-DSA NEW/Search-Engine-DSA/new_docs/csv_files'
